# Generated by Django 3.0 on 2019-12-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp2', '0003_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='dateTime',
            field=models.DateField(max_length=256),
        ),
    ]
