# Generated by Django 3.0 on 2019-12-27 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp2', '0004_auto_20191227_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='dateTime',
        ),
    ]
