# Generated by Django 3.0 on 2019-12-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp2', '0005_remove_blogpost_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='pic',
            field=models.ImageField(blank=True, upload_to='blogPics'),
        ),
    ]
