# Generated by Django 3.0 on 2019-12-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp2', '0006_blogpost_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='pic',
            field=models.ImageField(upload_to='blogPics'),
        ),
    ]
