# Generated by Django 3.0 on 2019-12-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp2', '0007_auto_20191229_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='pic',
            field=models.ImageField(upload_to='media'),
        ),
    ]
