# Generated by Django 3.0 on 2020-01-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp2', '0015_auto_20200101_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=256)),
                ('pic', models.ImageField(blank=True, upload_to='media')),
            ],
        ),
    ]
