# Generated by Django 3.0 on 2020-01-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp2', '0019_saveform_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saveform',
            name='ProfilePic',
        ),
    ]
