# Generated by Django 3.0.6 on 2020-05-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp2', '0022_auto_20200511_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
